### ISSUE TITLE
org.opensearch.client.sniff.Sniffer      : error while sniffing nodes

### ISSUE THREAD

**Issue by wvivek-infa** [opensearch-project/spring-data-opensearch#121]
### What is the bug?
org.opensearch.client.sniff.Sniffer      : error while sniffing nodes
java.net.ConnectException: Connection refused
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:953) ~[opensearch-rest-client-2.6.0.jar:2.6.0]
        at org.opensearch.client.RestClient.performRequest(RestClient.java:332) ~[opensearch-rest-client-2.6.0.jar:2.6.0]
        at org.opensearch.client.RestClient.performRequest(RestClient.java:320) ~[opensearch-rest-client-2.6.0.jar:2.6.0]
        at org.opensearch.client.sniff.OpenSearchNodesSniffer.sniff(OpenSearchNodesSniffer.java:121) ~[opensearch-rest-client-sniffer-2.5.0.jar:2.5.0]
        at org.opensearch.client.sniff.Sniffer.sniff(Sniffer.java:223) ~[opensearch-rest-client-sniffer-2.5.0.jar:2.5.0]
        at org.opensearch.client.sniff.Sniffer$Task.run(Sniffer.java:154) ~[opensearch-rest-client-sniffer-2.5.0.jar:2.5.0]

Spring Data 1.0.1 brings in the opensearch-rest-client-sniffer-2.5.0 dependency and the above error is reported repeatedly.

### What is the expected behavior?
Tried to disable sniffer as explained in https://stackoverflow.com/questions/73056569/how-do-i-stop-hibernate-search-from-sniffing-the-nodes-of-a-non-existent-local-e
Added exclusion for OpenSearchRestHighLevelClientAutoConfiguration and OpenSearchDataAutoConfiguration

None of the above helped and the exception is repeated.
The config is connecting to a cluster of 3 nodes. (All functionality is working. Able to connect to OpenSearch, persist and retrieve records.)

### What is your host/environment?
Redhat 8
Java 17
Spring Data OpenSearch - 1.0.1

### Do you have any additional context?
Connecting to OpenSearch 2.6.0 cluster.

**Comment by ayushpatel-av** [comment]
Same here any solution?

**Comment by NikitaHurynovich** [comment]
Workaround can be to exclude sniffer:
```
        <dependency>
            <groupId>org.opensearch.client</groupId>
            <artifactId>spring-data-opensearch-starter</artifactId>
            <version>1.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.opensearch.client</groupId>
                    <artifactId>opensearch-rest-client-sniffer</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by cunhap** [comment]
Also getting this error, would love a fix. :)

**Comment by dbt-lucka** [comment]
Not sure why this was closed? Is "excluding the sniffer" the proper solution or not?

**Comment by reta** [comment]
> Is "excluding the sniffer" the proper solution or not?

@dbt-lucka excluding the sniffer is the proper solution.

**Comment by dbt-lucka** [comment]
Ah thanks, that was the context I needed :-)
