### ISSUE TITLE
[FEATURE] Support Search templates

### ISSUE THREAD

**Issue by gquintillan** [opensearch-project/spring-data-opensearch#155]
### Is your feature request related to a problem?
I would like to use the `org.springframework.data.elasticsearch.core.query.SearchTemplateQuery` but I get this error when I try to use it: 

```
java.lang.IllegalArgumentException: unhandled Query implementation org.springframework.data.elasticsearch.core.query.SearchTemplateQuery
	at org.opensearch.data.client.orhlc.RequestFactory.getQuery(RequestFactory.java:1174) ~[spring-data-opensearch-1.2.0.jar:na]
	at org.opensearch.data.client.orhlc.RequestFactory.searchRequest(RequestFactory.java:752) ~[spring-data-opensearch-1.2.0.jar:na]
	at org.opensearch.data.client.orhlc.OpenSearchRestTemplate.search(OpenSearchRestTemplate.java:375) ~[spring-data-opensearch-1.2.0.jar:na]
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:492) ~[spring-data-elasticsearch-5.1.2.jar:5.1.2]
```

### What solution would you like?
Support `org.springframework.data.elasticsearch.core.query.SearchTemplateQuery` in https://github.com/opensearch-project/spring-data-opensearch/blob/b671763a47521e91ce3f677ebe48dfab59d8e631/spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RequestFactory.java#L1193

### Do you have any additional context?
[Search Templates](https://opensearch.org/docs/latest/search-plugins/search-template) are way to move the query logic to OpenSearch and make the code cleaner in the microservice side. Moreover this queries are more efficient since they are precompiled.

Example of use of query templates can be seen here: https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/antora/modules/ROOT/pages/elasticsearch/misc.adoc 

```
public class PersonCustomRepositoryImpl implements PersonCustomRepository {

  private final ElasticsearchOperations operations;

  public PersonCustomRepositoryImpl(ElasticsearchOperations operations) {
    this.operations = operations;
  }

  @Override
  public SearchPage<Person> findByFirstNameWithSearchTemplate(String firstName, Pageable pageable) {

    var query = SearchTemplateQuery.builder()                               (1)
      .withId("person-firstname")                                           (2)
      .withParams(
        Map.of(                                                             (3)
          "firstName", firstName,
          "from", pageable.getOffset(),
          "size", pageable.getPageSize()
          )
      )
      .build();

    SearchHits<Person> searchHits = operations.search(query, Person.class); (4)

    return SearchHitSupport.searchPageFor(searchHits, pageable);
  }
}
```

**Comment by gquintillan** [comment]
I see that it. might be supported in a different way using `NativeSearchQueryBuilder.withSearchTemplate`: 

https://github.com/opensearch-project/spring-data-opensearch/blob/425d1795c8710193efd910b249c58f70e7b88349/spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/NativeSearchQueryBuilder.java#L163C41-L163C55

Can someone provide an example? I don't know how to get an instance of `OpenSearchClient` which is needed in this constructor: https://github.com/opensearch-project/OpenSearch/blob/db90a415ff2fd428b4f7b3f800a51dc229287cb4/modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateRequestBuilder.java#L48
