### ISSUE TITLE
Occasional 502 Bad Gateway when sniffing nodes

### ISSUE THREAD

**Issue by pavelpp-topia** [opensearch-project/spring-data-opensearch#250]
We use opensearch with springboot 3 application and after upgrading to springboot 3 I see a lot of noise in our Rollbar and Datadog from opensearch component:
```

org.opensearch.client.ResponseException: method [GET], host [https://vpc-search-api-********.eu-central-1.es.amazonaws.com], URI [/_nodes/http?timeout=1000ms], status line [HTTP/1.1 502 Bad Gateway]
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

	at org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:345)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:320)
	at org.opensearch.client.sniff.OpenSearchNodesSniffer.sniff(OpenSearchNodesSniffer.java:121)
	at org.opensearch.client.sniff.Sniffer.sniff(Sniffer.java:223)
	at org.opensearch.client.sniff.Sniffer$Task.run(Sniffer.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Most errors don't have any additional info:

```
org.apache.http.ConnectionClosedException: Connection is closed
	at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:941)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:332)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:320)
	at org.opensearch.client.sniff.OpenSearchNodesSniffer.sniff(OpenSearchNodesSniffer.java:121)
	at org.opensearch.client.sniff.Sniffer.sniff(Sniffer.java:223)
	at org.opensearch.client.sniff.Sniffer$Task.run(Sniffer.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.ConnectionClosedException: Connection is closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	... 1 more
```

The weird part is that about half of these requests succeed according to Datadog, and for some time after service restart there are no errors at all, but they start occurring more and more often the longer service is up.

Our cluster is 1 to 2 nodes depending on environment and this error is observed in every environment.

Dependency is `implementation("org.opensearch.client:spring-data-opensearch-starter:1.2.0")`
Cluster is currently on Elasticsearch 7.10

**Comment by kedbirhan** [comment]
this might be related to [https://github.com/opensearch-project/spring-data-opensearch/issues/136](url) issue.

**Comment by pavelpp-topia** [comment]
> this might be related to [https://github.com/opensearch-project/spring-data-opensearch/issues/136](url) issue.

Thanks, it worked
