### ISSUE TITLE
[BUG] Compatiblity is broken with spring-data-elasticsearch

### ISSUE THREAD

**Issue by ms-semarchy** [opensearch-project/spring-data-opensearch#383]
### What is the bug?
When using `findByXXX` method of a repository:
```
java.lang.NoSuchMethodError: 'void org.springframework.data.elasticsearch.core.document.SearchDocumentResponse.<init>(long, java.lang.String, float, java.lang.String, java.lang.String, java.util.List, org.springframework.data.elasticsearch.core.AggregationsContainer, org.springframework.data.elasticsearch.core.suggest.response.Suggest, org.springframework.data.elasticsearch.core.SearchShardStatistics)'
	at org.opensearch.data.client.orhlc.SearchDocumentResponseBuilder.from(SearchDocumentResponseBuilder.java:112)
	at org.opensearch.data.client.orhlc.SearchDocumentResponseBuilder.from(SearchDocumentResponseBuilder.java:63)
	at org.opensearch.data.client.orhlc.OpenSearchRestTemplate.search(OpenSearchRestTemplate.java:410)
	at org.springframework.data.elasticsearch.repository.query.AbstractElasticsearchRepositoryQuery.execute(AbstractElasticsearchRepositoryQuery.java:123)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:170)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:149)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
	at jdk.proxy3/jdk.proxy3.$Proxy129.findByTenantName(Unknown Source)

```
-> `SearchDocumentResponseBuilder` constructs a`SearchDocumentResponse` with the wrong number of parameters.

It seems this has been resolved in recent commit https://github.com/opensearch-project/spring-data-opensearch/commit/6b99d035b05cca4af057bc7d1d42ffef682a1139#diff-0aae784663738295d836a70c4f548cbc8287b056a37f225133f967bbdb830cc8R121

But version 1.6.0 is still not available.

### How can one reproduce the bug?

* Create a repository for an index
* populate data in the index
* implement a find method an run it

### What is the expected behavior?
Should not fail and work like the previous version.

### What is your host/environment?
spring-data-opensearch-starter 1.5.4
spring-boot 3.4.0

MacOS arm64 / Java 21

**Comment by reta** [comment]
@ms-semarchy the  Spring Data OpenSearch with SB 3.4 support is not yet released
